name: tronapi

services:
  tronapi:
    build:
      context: .
      dockerfile: Dockerfile
    dns: 8.8.8.8
    environment:
      API_KEY: ${API_KEY}
      DBADDR: db:5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8000:8000
    depends_on: 
      - db
      - tests
    volumes:
      - ./src/tronapi:/app/tronapi
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      API_KEY: ${API_KEY}
      DBADDR: db:5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on: 
      - db
    volumes:
      - ./src/tronapi:/app/tronapi
  db:
    image: postgres:17-alpine
    shm_size: 128mb
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
